### ISSUE TITLE
Can it also work on game text?

### ISSUE THREAD

**Issue by kao0312** [crskycode/TmrHiro_Tool#2]
I unpacked the game text (.srp) using Garbro, but I don't know how to package it back (.pac).
```Usage:
  Extract   : GrdTool -e [image.grd|folder]
  Create    : GrdTool -c [image.png|folder]

Help:
  This tool is only works with 'Tmr-Hiro GRD' files,
    please check the engine first.
  Metadata (.metadata.json) and image (.png) are required to build GRD.
```

**Comment by Cosetto** [comment]
https://github.com/Cosetto/Visual-novel-archive-tools/tree/master/TmrHiro
create grd_2.pac

**Comment by kao0312** [comment]
Thank you very much.
In fact, I have already tried your tool. Please refer to the discussion in this [post](https://www.ai2moe.org/topic/3517-%E3%80%90500%E8%90%8C%E6%B1%81%E3%80%91%E6%B1%82tmr-hiro-adv-system%E5%BC%95%E6%93%8E%E6%96%87%E6%9C%AC%E5%B0%81%E5%8C%85%E6%88%96%E5%85%8D%E5%B0%81/#comment-26160) for details.
You can use machine translation to translate this post. Let me briefly explain: Your tool may not be suitable for this game. After using your tool to unpack the game text, I directly repackaged these text files, but the game could not be launched. In the end, Satan provided a solution - slightly modifying ssynn's tool.

> https://github.com/satan53x/game_translation 
> You need to change the entry_offset_length from 8 to 4 in public_function.py. (Currently on line 2249.)
